# Generated by Django 3.2.4 on 2021-08-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datamart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('incative', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSimple', models.CharField(choices=[('text', 'TEXT'), ('text(#)', 'TEXT(#)'), ('number', 'NUMBER'), ('number(#,#)', 'NUMBER(#,#)')], max_length=50)),
                ('typeDataBase', models.CharField(choices=[('int', 'INT'), ('varchar(250)', 'VARCHAR(250)'), ('varchar(#)', 'VARCHAR(#)'), ('char(1)', 'CHAR(1)'), ('double(14,4)', 'DOUBLE(14,4)'), ('double(#,#)', 'DOUBLE(#,#)')], max_length=50)),
            ],
            options={
                'ordering': ('-typeSimple',),
            },
        ),
        migrations.CreateModel(
            name='TableDataMart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datamart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_datamart', to='application.datamart')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ColumnDataMart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_datamart', to='application.tabledatamart')),
                ('typeSimple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_typeSimple', to='application.typedata')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
