# Generated by Django 3.2.4 on 2021-09-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamartConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('datamart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datamart_datamart_connection', to='application.datamart')),
            ],
        ),
    ]
