# Generated by Django 3.2.4 on 2021-08-17 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeData', models.CharField(choices=[('integer', 'Integer'), ('varchar', 'Varchar')], max_length=50)),
            ],
            options={
                'ordering': ('-typeData',),
            },
        ),
        migrations.AlterModelOptions(
            name='datamart',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='datamart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datamart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('incative', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='TableDataMart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datamart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas', to='application.datamart')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ColumnDataMart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='application.tabledatamart')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
