# Generated by Django 3.2.4 on 2021-08-17 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210817_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedata',
            options={'ordering': ('-type',)},
        ),
        migrations.RemoveField(
            model_name='typedata',
            name='typeData',
        ),
        migrations.AddField(
            model_name='columndatamart',
            name='type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='application.typedata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typedata',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
